AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-auth-app

  Sample SAM Template for sam-auth-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  FrontendOrigin:
    Type: String
    Default: "http://localhost:5173"

Resources:
  AuthChallengesLambdas:
    Type: AWS::Serverless::Application
    Properties:
      Location: src\Lambdas\template_auth_challenges.yaml
        
  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: src\Cognito\template.yaml
      Parameters:
        FrontendOrigin: !Ref FrontendOrigin
        CaptchaDefineAuthChallengeARN: !GetAtt AuthChallengesLambdas.Outputs.CaptchaDefineAuthChallengeARN
        CaptchaCreateAuthChallengeARN: !GetAtt AuthChallengesLambdas.Outputs.CaptchaCreateAuthChallengeARN
        CaptchaVerifyAuthChallengeARN: !GetAtt AuthChallengesLambdas.Outputs.CaptchaVerifyAuthChallengeARN
        
  EndpointLambdas:
    Type: AWS::Serverless::Application
    Properties:
      Location: src\Lambdas\template_endpoints.yaml
      Parameters:
        AuthAppUserPoolARN: !GetAtt Cognito.Outputs.AuthAppUserPoolARN
        AuthAppUserPoolClientID: !GetAtt Cognito.Outputs.AuthAppUserPoolClientID
        FrontendOrigin: !Ref FrontendOrigin
