AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-auth-app

  Sample SAM Template for sam-auth-app

Parameters:
  FrontendOrigin:
    Type: String
    Default: "http://localhost:5173"

Resources:
  LambdasAuthChallenges:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates\lambdas_auth_challenges.yaml
        
  CognitoAuthUserPool:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates\cognito_auth_user_pool.yaml
      Parameters:
        FrontendOrigin: !Ref FrontendOrigin
        CaptchaDefineAuthChallengeARN: !GetAtt LambdasAuthChallenges.Outputs.CaptchaDefineAuthChallengeARN
        CaptchaCreateAuthChallengeARN: !GetAtt LambdasAuthChallenges.Outputs.CaptchaCreateAuthChallengeARN
        CaptchaVerifyAuthChallengeARN: !GetAtt LambdasAuthChallenges.Outputs.CaptchaVerifyAuthChallengeARN

  LambdaEndpointsExecutionRoleARN:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates\permissions_endpoints.yaml

  LambdasEndpoints:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates\lambdas_endpoints.yaml
      Parameters:
        LambdaEndpointsExecutionRoleARN: !GetAtt LambdaEndpointsExecutionRoleARN.Outputs.LambdaEndpointsExecutionRoleARN
        AuthUserPoolARN: !GetAtt CognitoAuthUserPool.Outputs.AuthUserPoolARN
        AuthUserPoolClientID: !GetAtt CognitoAuthUserPool.Outputs.AuthUserPoolClientID
        FrontendOrigin: !Ref FrontendOrigin

  CognitoUserRoles:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates\cognito_user_roles.yaml
      Parameters:
        AuthUserPoolID: !GetAtt CognitoAuthUserPool.Outputs.AuthUserPoolID
        AuthAppRestApiID: !GetAtt LambdasEndpoints.Outputs.AuthAppRestApiID