AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-auth-app
  Cognito Template for sam-auth-app

Parameters:
  AuthUserPoolID:
    Type: String
  AuthAppRestApiID:
    Type: String

Resources:
  ModeratorGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: "Content moderators"
      UserPoolId: !Ref AuthUserPoolID
      Precedence: 20
      RoleArn: !GetAtt ModeratorRole.Arn

  UserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: "Regular users"
      UserPoolId: !Ref AuthUserPoolID
      Precedence: 30
      RoleArn: !GetAtt UserRole.Arn

  ModeratorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cognito-idp.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "ModeratorAPIAccess"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: execute-api:Invoke
                Resource:
                  - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AuthAppRestApiID}/*/GET/admin/*"
                  - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AuthAppRestApiID}/*/POST/admin/*"

  UserRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cognito-idp.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "UserBasicAccess"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: execute-api:Invoke
                Resource:
                  - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AuthAppRestApiID}/*/GET/public/*"
              - Effect: Deny
                Action: execute-api:Invoke
                Resource:
                  - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AuthAppRestApiID}/*/GET/admin/*"
                  - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AuthAppRestApiID}/*/POST/admin/*"
