AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-auth-app
  Cognito Template for sam-auth-app

Parameters:
  ExampleCallbackURL:
    Type: String
    Default: "http://localhost:5173/social-login-confirm-code"
  FrontendOrigin:
    Type: String
  CaptchaDefineAuthChallengeARN:
    Type: String
  CaptchaCreateAuthChallengeARN:
    Type: String
  CaptchaVerifyAuthChallengeARN:
    Type: String

Resources:
  AuthUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: AuthUserPool
      Schema:
        - Name: captcha_completed
          AttributeDataType: Boolean
          Mutable: true
          Required: false
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          PasswordHistorySize: 22
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      LambdaConfig:
        DefineAuthChallenge: !Ref CaptchaDefineAuthChallengeARN
        CreateAuthChallenge: !Ref CaptchaCreateAuthChallengeARN
        VerifyAuthChallengeResponse: !Ref CaptchaVerifyAuthChallengeARN
      AutoVerifiedAttributes:
        - email

  AuthUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: AuthUserPoolIdentityProvider
    Properties:
      AllowedOAuthFlowsUserPoolClient: true
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_CUSTOM_AUTH
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
      SupportedIdentityProviders:
        - COGNITO
        - Google
      UserPoolId: !Ref AuthUserPool
      CallbackURLs:
        - !Ref ExampleCallbackURL
        - !Ref FrontendOrigin
      LogoutURLs:
        - !Ref FrontendOrigin

  AuthUserPoolIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref AuthUserPool
      ProviderName: "Google"
      ProviderDetails:
        client_id: '{{resolve:secretsmanager:google_api_credentials:SecretString:client_id}}'
        client_secret: '{{resolve:secretsmanager:google_api_credentials:SecretString:client_secret}}'
        authorize_scopes: "profile email openid"
      ProviderType: "Google"
      AttributeMapping:
        email: "email"

  AuthUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub user-pool-domain-${AWS::AccountId}-${AWS::Region}
      UserPoolId: !Ref AuthUserPool

  AuthIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub 'AuthAppIdentityPool'
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref AuthUserPoolClient
          ProviderName: !GetAtt AuthUserPool.ProviderName

Outputs:
  AuthUserPoolID:
    Description: 'AuthUserPool ID'
    Value: !Ref AuthUserPool
  AuthUserPoolClientID:
    Description: 'AuthUserPoolClient ID'
    Value: !Ref AuthUserPoolClient
  AuthUserPoolARN:
    Description: 'AuthUserPool ARN'
    Value: !GetAtt AuthUserPool.Arn
