AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-auth-app

  Lambda Template for sam-auth-app

Parameters:
  LambdaEndpointsExecutionRoleARN:
    Type: String
  AuthUserPoolARN:
    Type: String
  AuthUserPoolClientID:
    Type: String
  FrontendOrigin:
    Type: String

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    CodeUri: ../src/ 
    Runtime: python3.12
    Environment:
      Variables: 
        USER_POOL_CLIENT: !Ref AuthUserPoolClientID
        ALLOWED_ORIGIN: !Sub
          - "'${Origin}'"
          - Origin: !Ref FrontendOrigin

Resources:  
  AuthAppRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref AuthUserPoolARN
            Identity:
              Header: Authorization
              ReauthorizeEvery: 3000
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Accept,Accept-Encoding,Accept-Language,User-Agent,Access-Control-Allow-Origin'"
        AllowOrigin: !Sub
          - "'${Origin}'"
          - Origin: !Ref FrontendOrigin
  
  SignUp:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SignUp
      Handler: functions.endpoints.sign_up.lambda_handler
      Role: !Ref LambdaEndpointsExecutionRoleARN
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /sign_up
            Method: POST
            RestApiId: !Ref AuthAppRestApi
            Auth:
              Authorizer: NONE

  SignInSocialCallback:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SignInSocialCallback
      Handler: functions.endpoints.sign_in_social_callback.lambda_handler
      Role: !Ref LambdaEndpointsExecutionRoleARN
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /sign_in_social_callback
            Method: POST
            RestApiId: !Ref AuthAppRestApi
            Auth:
              Authorizer: NONE

  SignInCustomAuth:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SignInCustomAuth
      Handler: functions.endpoints.sign_in_custom_auth.lambda_handler
      Role: !Ref LambdaEndpointsExecutionRoleARN
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /sign_in_custom_auth
            Method: POST
            RestApiId: !Ref AuthAppRestApi

  ConfirmSignUp:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ConfirmSignUp
      Handler: functions.endpoints.confirm_sign_up.lambda_handler
      Role: !Ref LambdaEndpointsExecutionRoleARN
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /confirm_sign_up
            Method: POST
            RestApiId: !Ref AuthAppRestApi
            Auth:
              Authorizer: NONE

  Protected:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Protected
      Handler: functions.endpoints.sign_up.lambda_handler
      Role: !Ref LambdaEndpointsExecutionRoleARN
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /protected
            Method: POST
            RestApiId: !Ref AuthAppRestApi

Outputs:
  AuthAppRestApiID:
    Description: ID of the AuthApp Rest API
    Value: !Ref AuthAppRestApi