AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-auth-app

  Lambda Template for sam-auth-app

Parameters:
  AuthAppUserPoolClientID:
    Type: String

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    CodeUri: ./
    Runtime: python3.12
    Environment:
      Variables:
        LOG_LEVEL: "info"
        STAGE: "prod"


Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CognitoSignUpPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:SignUp
                Resource: "*"
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  
  AuthAppRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
  
  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SignUpFunction
      Handler: functions/sign_up.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables: 
          USER_POOL_CLIENT: !Ref AuthAppUserPoolClientID
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /sign_up
            Method: POST
            RestApiId: !Ref AuthAppRestApi
      
