AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-auth-app

  Lambda Template for sam-auth-app

Parameters:
  AuthAppUserPoolClientID:
    Type: String
  FrontendOrigin:
    Type: String

Resources:
  Endpoints:
    Type: AWS::Serverless::Application
    Properties:
      Location: template_endpoints.yaml
      Parameters:
        AuthAppUserPoolClientID: !Ref AuthAppUserPoolClientID
        FrontendOrigin: !Ref FrontendOrigin

  AuthChallenges:
    Type: AWS::Serverless::Application
    Properties:
      Location: template_auth_challenges.yaml
      Parameters:
        AuthAppUserPoolClientID: !Ref AuthAppUserPoolClientID
        FrontendOrigin: !Ref FrontendOrigin