AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-auth-app

  Lambda Template for sam-auth-app

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    CodeUri: functions/
    Runtime: python3.12
    Environment:
      Variables:
        LOG_LEVEL: "info"
        STAGE: "prod"


Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CognitoSignUpPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:SignUp
                Resource: "*"
  
  AuthAppRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
  
  SignUpLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SignUpLambdaFunction
      Handler: sign_up.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /sign_up
            Method: get
            RestApiId: !Ref AuthAppRestApi
      
