AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-auth-app

  Lambda Template for sam-auth-app

Resources:
  SignUpLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SignUpLambdaFunction
      Handler: sign_up.lambda_handler
      CodeUri: functions/
      Runtime: python3.12
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:SignUp
              Resource: "*"

Outputs:
  SignUpLambdaIntegrationUri:
    Description: "API Gateway Lambda Integration URI"
    Value: 
      Fn::Sub: 
        - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations"
        - LambdaFunctionArn: !GetAtt SignUpLambdaFunction.Arn
  
  SignUpLambdaIntegrationArn:
    Description: "API Gateway Lambda Integration Arn"
    Value: !GetAtt SignUpLambdaFunction.Arn
